sudo: false
language: node_js
node_js: '5'
addons:
  postgresql: '9.4'
before_script:
  - bash install.sh
script:
  - source env.sh && npm run test
notifications:
  slack: 'testing-bot:nDUQ4XTKW6m9VrTW89ByLxtA#general'
deploy:
  app: immense-chamber-14538
  provider: heroku
  api_key:
    secure: bbda3a29-9d67-4f55-bddf-d3e8bcc99247
